# General
CanvaSize={W=1600, H=800}
BackgroundColor={R=92, G=255, B=230, A=255}
OverlayMarginSize=20
OverlayColor={R=0, G=0, B=0, A=180}

# Fonts
FontsDir="fonts/"

# Text
TextSize=30
TextColor={R=255, G=255, B=255, A=255}

# Title
AttendanceTitle="CERTIFICADO DE PARTICIPAÇÃO"
SpeakerTitle="CERTIFICADO DE PALESTRANTE"
TitleTextSize=80
TitleTextColor={R=255, G=255, B=255, A=255}

# Person
PersonTextSize=70

# Validator
ValidatorMinLength=8
ValidatorMaxLength=11
ValidatorTextSize=20
ValidatorTextColor={R=255, G=255, B=255, A=85} # same as text color with 1/3 of the alpha

# Signature
SignatureDir="signatures/"
SignatureLineLength=22
SignatureImgSize=100
SignatureTextSize=60
SignatureTextColor={R=255, G=255, B=255, A=255}
SignatureTitleSize=15
SignatureTitleColor={R=255, G=255, B=255, A=255}

# Output -> USAR SQLITE
OutputDir="output/"
DefaultFileName="_output.json"
