name: 'certifigo-cli release'

on:
  push:
    tags:
      - 'v*' # run on new version tag (v0.1.0)

permissions:
  contents: 'write'
  packages: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
            # 0 indicates all history for all branches and tags
            fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.24'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v1'
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: certifigo-cli
          path: ./dist/*
